### ISSUE TITLE
How to turn it back on again?

### ISSUE THREAD

**Issue by hotmailbelike** [maateen/battery-monitor#109]
I have installed the Battery Monitor software in Ubuntu 20.04.
I want to know how to start it again after my machine restarts?
Also, how to set notification when battery level reaches a certain level?

Thank you

**Comment by maateen** [comment]
Are you using the daily build from [here](https://github.com/maateen/battery-monitor#linux-64-bit) or using the last release?

> I want to know how to start it again after my machine restarts?

This tool should be started automatically. Also, you can check the status and start it with the following commands:

```shell
$ systemctl status battery-monitor
$ systemctl start battery-monitor
```

> Also, how to set notification when battery level reaches a certain level?

For the daily build version, please edit `/etc/battery-monitor/config.toml` file to set a notification when the battery level reaches a certain level. (The integer values indicate to battery level in percentage.)

 ```shell
$ cat /etc/battery-monitor/config.toml
```
```toml
critical_battery_warning_at = 10
low_battery_warning_at = 30
first_custom_warning_at = 50
second_custom_warning_at = 75
third_custom_warning_at = 90
notification_stability = 5
```

After that, please restart it with the following command:

```shell
$ systemctl restart battery-monitor
```

I am adding these in the README.
